### PR TITLE
Bilinear transform and Butterworth filters

### PR DESCRIPTION
**Pull request by Fylax**
Starting from [this discussion](https://discuss.mathdotnet.com/t/bilinear-transform-and-butterworth-filters/832) I am proposing an implementation for the Butterworth filters.
In order to make it work, I implemented:
- Bilinear transform
- Butterworth designer
- Butterworth IIR coefficients calculator

In particular, the bilinear tranform should work with any LTI, so it might be possible to implement it inside the base `Numerics` package, but for sure it will work with any possible future filter implementation.

I have added some unit tests for the designed filters: the expected values have been computed using Octave.

### CODE REVIEW

**Comment by Fylax** [comment]
Travis with mono seems to fail due to missing ValueTuple (that I referenced as nuget package for .NET Framework version < 4.7)

Nevertheless, mono documentation seems to suggest that adding that package should make the trick.
Any idea regarding the issue?

**Comment by cdrnet** [comment]
Thanks!

According to the logs, it seems the problem is that the `System.ValueType` type is available twice now, once in mscorlib and once in System.ValueTuple. Maybe the problem already goes away if the reference is managed by Paket. I'll have a look.

**Comment by Fylax** [comment]
Hello.

I managed to let paket handle the `System.ValueTuple` package (removing it from the project definition).
Sadly this did not resolve the problem, but [here](https://github.com/dotnet/corefx/issues/32561) it seems to be a NetStandard 2.0 related issue.

**Comment by cdrnet** [comment]
I've finally pulled this into master - thanks a lot!

(pulled in directly, bypassing the PR)

**Pull request closed without merging**
